Repository Coffee-ing/Server, pull requests merged in 2023-11, with the labels that each got.

#2 [Feat] 모임 검색 (#1)
  coffeeing/settings.py
  coffeeing/urls.py
  main/migrations/0001_initial.py
  main/migrations/0002_club_meet_time.py
  main/models.py
  main/serializers.py
  main/urls.py
  main/views.py
  myvenv/Scripts/normalizer.exe
Labels: feature

#7 [Feat] 모임 신청 (#5)
  main/migrations/0003_myclub.py
  main/models.py
  main/urls.py
  main/views.py
Labels: feature

#10 [Feat] 모임 찜하기/찜해제 (#8)
  coffeeing/urls.py
  main/migrations/0001_initial.py
  main/migrations/0003_myclub.py
  main/models.py
  main/serializers.py
  main/urls.py
  main/views.py
Labels: feature

#11 [Chore] 검색 키워드 조건 수정 (#1)
  main/views.py
Labels: enhancement

#13 [Feat] 내가 신청한 모임 조회 (#12)
  coffeeing/urls.py
  mypage/serializers.py
  mypage/urls.py
  mypage/views.py
Labels: feature

#15 [Feat] 신청한 모임 취소 (#14)
  mypage/serializers.py
  mypage/urls.py
  mypage/views.py
Labels: enhancement, feature

#17 [Feat / Chore] 내가 찜한 모임 조회 (#16) / 신청한 모임 조회 (#12) 및 삭제 (#14) 수정
  mypage/serializers.py
  mypage/urls.py
  mypage/views.py
Labels: enhancement, feature

#19 [Feat] 내가 주최한 모임 보기 (#18)
  main/views.py
  mypage/urls.py
  mypage/views.py
Labels: feature
